url: southwestiesabq.com
baseurl: ""

# Site settings
title: SouthWesties ABQ
email: southwestiesabq@gmail.com
description: "West Coast Swing in Albuquerque, New Mexico"
logo:
- path: img\logos\southwestiesabq-black.png
  height: 60 #height in px, defaults to 52px


# Team names, titles and social links
people:
- name: Elaine Rhoades
  pic: elaine_rhoades
  position: President
  pronouns: She/They

- name: Craig Hogle
  pic: craig_hogle
  position: Treasurer
  pronouns: He/Him

- name: Jason Torchinsky
  pic: jason_torchinsky
  position: Secretary
  pronouns: They/Them

# Social networks usernames (options: twittwer, facebook, stack-overflow, 
# bitbucket, github, google-plus, flickr, dribbble, pinterest, instagram, 
# tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/southwestiesabq/
  - title: instagram
    url: https://www.instagram.com/southwestiesabq/


# Postal address (add as many lines as necessary)
address:
  - line: P.O. Box 50611
  - line: Albuquerque NM, 87181

# Build settings
markdown: kramdown
permalink: pretty